apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-gateway:v1
          image: smachida/ms-demo-13-run-on-k8s-gateway:v1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod"
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
