apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: ms-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-authorization-server
          image: smachida/ms-demo-13-run-on-k8s-authorization-server
          #image: smachida/ms-demo-13-run-on-k8s-authorization-server:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          envFrom:
            - secretRef:
                name: config-client-credentials
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 300Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - port: 80
      targetPort: 80
