apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: ms-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-config-server
          image: smachida/ms-demo-13-run-on-k8s-config-server
          #image: smachida/ms-demo-13-run-on-k8s-config-server:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,native"
          envFrom:
            - secretRef:
                name: config-server-secrets
          ports:
            - containerPort: 8888
          resources:
            limits:
              memory: 300Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: config-repo-volume
              mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: ms-demo2  
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
