apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ms-demo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-gateway
          image: smachida/ms-demo-13-run-on-k8s-gateway
          #image: smachida/ms-demo-13-run-on-k8s-gateway:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: config-client-credentials
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 300Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 80
      nodePort: 31080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
spec:
#  loadBalancerIP: 172.18.255.200
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
