apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ms-demo2  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-product-service
          image: smachida/ms-demo-13-run-on-k8s-product-service
          #image: smachida/ms-demo-13-run-on-k8s-product-service:v1
          #image: smachida/ms-demo-13-run-on-k8s-product-service:v2
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: config-client-credentials
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 300Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ms-demo2  
spec:
  selector:
    app: product
  ports:
    - port: 80
      targetPort: 80
