apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
  namespace: ms-demo  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          #image: 172.16.140.11/ms-demo/ms-demo-13-run-on-k8s-review-service
          image: smachida/ms-demo-13-run-on-k8s-review-service
          #image: smachida/ms-demo-13-run-on-k8s-review-service:v1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: config-client-credentials
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1024Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/info
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: review
spec:
  selector:
    app: review
  ports:
    - port: 80
      targetPort: 80
