apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ms-demo2  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql/mysql-server
          volumeMounts:
            - name: initdb-mysql-review
              mountPath: /docker-entrypoint-initdb.d
          args:
          #  - "--ignore-db-dir=lost+found"
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_bin"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: review-db
            - name: MYSQL_USER
              value: vmware
            - name: MYSQL_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 1024Mi
      volumes:
        - name: initdb-mysql-review
          configMap:
            name: initdb-mysql-review
            items:
              - key: entry.sql
                path: entry.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ms-demo2  
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
